/**
 * Helper to make reducerify compatible with Jotai
 *
 * This module provides utilities to use reducers generated by
 * reducerify with Jotai atoms.
 */

import { atom, type WritableAtom } from 'jotai';

/**
 * Type helper to extract the union action type from action creators
 */
export type ActionsToActionType<Actions extends Record<string, (...args: any[]) => any>> =
  ReturnType<Actions[keyof Actions]>;

/**
 * Creates a Jotai atom from a reducerify reducer using
 * atom composition. This approach is more idiomatic in Jotai.
 *
 * @example
 * ```ts
 * const { reducer, actions } = forState<State>().createReducer({
 *   increment: (state) => ({ count: state.count + 1 }),
 * });
 *
 * const counterAtom = atomWithReducerify(
 *   { count: 0 },
 *   reducer,
 *   'counterAtom' // Optional debug label for Jotai DevTools
 * );
 *
 * // Usage
 * const [state, dispatch] = useAtom(counterAtom);
 * dispatch(actions.increment());
 * ```
 */
export function atomWithReducerify<State, Actions extends Record<string, (...args: any[]) => any>>(
  initialState: State,
  reducer: (state: State, action: ActionsToActionType<Actions>) => State,
  debugLabel?: string,
): WritableAtom<State, [ActionsToActionType<Actions>], void> {
  type Action = ActionsToActionType<Actions>;

  // Base atom to store the state
  const baseAtom = atom<State>(initialState);

  // Assign debug labels if provided (for Jotai DevTools)
  if (debugLabel) {
    baseAtom.debugLabel = `${debugLabel}:base`;
  }

  // Derived atom with getter and setter
  const resultAtom = atom(
    (get) => get(baseAtom),
    (get, set, action: Action) => {
      const currentState = get(baseAtom);
      const newState = reducer(currentState, action);
      set(baseAtom, newState);
    },
  );

  if (debugLabel) {
    resultAtom.debugLabel = debugLabel;
  }

  return resultAtom;
}
